### ISSUE TITLE
Implement Ready to Play automation

### ISSUE THREAD

**Issue by yeliknewo** [bdatdo0601/Discord-Bot-Boi#18]
People should be able to add the Ready to Play role to mark they want to play any game. When they no longer want to play they should remove the Ready to Play role. If they forget to remove the Ready to Play role the bot should do it for them after a reasonable amount of time. It might be good to notify the user in a PM they were removed from the role.

**Comment by bdatdo0601** [comment]
Maybe when they switched to idle?
